### ISSUE TITLE
Set up CRUD for Tasks

### ISSUE THREAD

**Issue by lisbethmachado** [jessicablank/spacebook-mars#23]
- [x] set up CRUD routes for task input form
-Post method
-Get method
-Delete method
(-Update if time permits)
- [x] use taskAPI to send requests to database
- [x] use task Model to store input elements from task Form
- [x] Set up handleDelete function for deleting tasks by id

**Comment by jessicablank** [comment]
Routes are set-up in the taskAPI.js file. 
Ask John 

- [ ] if they need to be split up to work better on the front end.
